import type { Depth } from "./depth";

/** What the user wants explained / discussed about a stock. */
export type ExplainKind =
  | "metric" // explain one metric for this stock
  | "overview" // plain strengths + watch-outs summary
  | "bearcase" // steel-man the bear case (de-bias)
  | "bullcase" // steel-man the bull case
  | "price" // what the price action means
  | "question" // free-form "ask anything", grounded in the stock
  | "journal"; // critique the reasoning quality of a user's thesis

export interface ExplainRequest {
  ticker: string;
  depth: Depth;
  kind: ExplainKind;
  /** required when kind === "metric" */
  metricKey?: string;
  /** required when kind === "question" */
  question?: string;
  /** required when kind === "journal" */
  thesis?: string;
  /** optional horizon for journal critique, e.g. "3 months" */
  horizon?: string;
}

export interface ExplainResponse {
  answer: string;
  /** "ai" = generated by Claude; "static" = curated fallback (no API key) */
  source: "ai" | "static";
  depth: Depth;
  kind: ExplainKind;
  /** the resolved disclaimer, always present */
  disclaimer: string;
}
